# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jonwinters/code/dnslog

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jonwinters/code/dnslog

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jonwinters/code/dnslog/CMakeFiles /home/jonwinters/code/dnslog/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jonwinters/code/dnslog/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named routedns

# Build rule for target.
routedns: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 routedns
.PHONY : routedns

# fast build rule for target.
routedns/fast:
	$(MAKE) -f CMakeFiles/routedns.dir/build.make CMakeFiles/routedns.dir/build
.PHONY : routedns/fast

parsedns.o: parsedns.cpp.o

.PHONY : parsedns.o

# target to build an object file
parsedns.cpp.o:
	$(MAKE) -f CMakeFiles/routedns.dir/build.make CMakeFiles/routedns.dir/parsedns.cpp.o
.PHONY : parsedns.cpp.o

parsedns.i: parsedns.cpp.i

.PHONY : parsedns.i

# target to preprocess a source file
parsedns.cpp.i:
	$(MAKE) -f CMakeFiles/routedns.dir/build.make CMakeFiles/routedns.dir/parsedns.cpp.i
.PHONY : parsedns.cpp.i

parsedns.s: parsedns.cpp.s

.PHONY : parsedns.s

# target to generate assembly for a file
parsedns.cpp.s:
	$(MAKE) -f CMakeFiles/routedns.dir/build.make CMakeFiles/routedns.dir/parsedns.cpp.s
.PHONY : parsedns.cpp.s

routedns.o: routedns.cpp.o

.PHONY : routedns.o

# target to build an object file
routedns.cpp.o:
	$(MAKE) -f CMakeFiles/routedns.dir/build.make CMakeFiles/routedns.dir/routedns.cpp.o
.PHONY : routedns.cpp.o

routedns.i: routedns.cpp.i

.PHONY : routedns.i

# target to preprocess a source file
routedns.cpp.i:
	$(MAKE) -f CMakeFiles/routedns.dir/build.make CMakeFiles/routedns.dir/routedns.cpp.i
.PHONY : routedns.cpp.i

routedns.s: routedns.cpp.s

.PHONY : routedns.s

# target to generate assembly for a file
routedns.cpp.s:
	$(MAKE) -f CMakeFiles/routedns.dir/build.make CMakeFiles/routedns.dir/routedns.cpp.s
.PHONY : routedns.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... routedns"
	@echo "... parsedns.o"
	@echo "... parsedns.i"
	@echo "... parsedns.s"
	@echo "... routedns.o"
	@echo "... routedns.i"
	@echo "... routedns.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

